// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPCFoVqTDDxZUwMgfVrwBEX5lQARzdN4Y',
    appId: '1:422067880433:web:6a990560bddd9215540450',
    messagingSenderId: '422067880433',
    projectId: 'final-project-tcc-425305',
    authDomain: 'final-project-tcc-425305.firebaseapp.com',
    storageBucket: 'final-project-tcc-425305.firebasestorage.app',
    measurementId: 'G-36NWS0XW67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX_A6ESJh_xLb_B_sCn_ZirsYUrjSedZg',
    appId: '1:422067880433:android:270c1b922232d72c540450',
    messagingSenderId: '422067880433',
    projectId: 'final-project-tcc-425305',
    storageBucket: 'final-project-tcc-425305.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7GgDm72KxkHXxeHbbICObCZt2SYrjHG0',
    appId: '1:422067880433:ios:2a5611e9dfac473b540450',
    messagingSenderId: '422067880433',
    projectId: 'final-project-tcc-425305',
    storageBucket: 'final-project-tcc-425305.firebasestorage.app',
    iosBundleId: 'com.example.mounttravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7GgDm72KxkHXxeHbbICObCZt2SYrjHG0',
    appId: '1:422067880433:ios:2a5611e9dfac473b540450',
    messagingSenderId: '422067880433',
    projectId: 'final-project-tcc-425305',
    storageBucket: 'final-project-tcc-425305.firebasestorage.app',
    iosBundleId: 'com.example.mounttravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPCFoVqTDDxZUwMgfVrwBEX5lQARzdN4Y',
    appId: '1:422067880433:web:0916c6a18513254b540450',
    messagingSenderId: '422067880433',
    projectId: 'final-project-tcc-425305',
    authDomain: 'final-project-tcc-425305.firebaseapp.com',
    storageBucket: 'final-project-tcc-425305.firebasestorage.app',
    measurementId: 'G-G9CHLH6H5L',
  );

}